[package]
name = "visa-bindings"
version = "0.1.0"
edition = "2024"

[features]
bindgen = ["dep:bindgen"]

[dependencies]

[build-dependencies]
bindgen = { version = "0.72", optional = true}
